---
title: "Experiences"
author: 
date: 
output: 
  html_document:
    toc: true
    toc_float: true
---

## Education

Sep 2020 - Jun 2023, M.A. in Sociology (Gerontology), Institute of Population Research, [Peking University (PKU)](https://english.pku.edu.cn/)

Feb 2019 - Jun 2019, Exchange in Sociology, Department of Sociology, [National Taiwan University (NTU)](https://www.ntu.edu.tw/english/index.html) 

Sep 2016 - Jun 2020, B.A. in Public Affairs Administration, School of Sociology and Population Studies, [Renmin University of China (RUC)](https://www.ruc.edu.cn/en)


## Research Experiences

### Project supported by National Natural Science Foundation of China (2022-2024)
• Jan 2022 - Present

• RA in *Utility Evaluation and Improvement Path of Intelligent Technology in Promoting Aging Health*. Grant no.71373012

### Project supported by Tang Chung-ying Foundation (2022-2024)
• Sep 2021 - Present

• RA in *School Bullying Based on Gender Label and Sexual Orientation*. Grant no.050459

### Project supported by Beijing Municipal Bureau Statistics (2021-2022)

• Nov 2021 - Mar 2022

• RA in *Study on the Development of Women and Children in Beijing*. Grant no.8300400418

### Project supported by National Social Science Foundation of China (2018-2021)

• Sep 2020 - Sep 2021

• RA in *Long-term Effects of Early Life Events on Disability in a Whole-population, Life-cycle Perspective*. Grant no.18CRK005


## Grants

### The 30th Challenge Cup of PKU - Interdisciplinary Award Competition

• Nov 2021 - Jun 2022

• Participant in *Being and Seeing: A Study of Social Attitudes Toward Transgender*. Second Prize. (about $350)

### The 29th Challenge Cup of PKU - Youth Science Award Competition

• Nov 2020 - Jun 2021

• Leader in *Faith in the Twilight Years: An Exploration of the Religious Course of Chinese Older Adults*. Second Prize. (about $350)

### The Undergraduate Innovative Test Program of RUC

• May 2018 - Jun 2019

• Major participant in *The Status Quo and Influencing Factors of Chinese Ex-servicemen's Social Integration: An Empirical Study Based On Social Integration Theory*. (about $700)

### The Undergraduate Scientific Research Foundation Project of RUC

• May 2018 - Jun 2019

• Leader in *Labor or Need: Analysis on the Major Diversion System of Colleges and Universities*. (about $700)

##	Awards & Honors

• 2021-2022 National Scholarship, Minister of Education of China

• 2021-2022 The First Prize Scholarship, PKU

• 2021-2022 Outstanding Student Award, PKU

• 2020 Outstanding Graduate, RUC

• 2017-2019 National Encouragement Scholarship, Minister of Education of China

• 2018 Outstanding Student Award, RUC

## Courses

• **Population Health**: Social Medicine, Epidemiology of Population and Health, Social Research on Population and Reproductive Health, Topics in Health Economics

• **Demography**: Introduction to Demography, Demographic Statistics, Population Sociology, Population: Issues and Research

• **Sociology**: Introduction to Sociology, Social Science Research: Theory & Practice 

• **Economics**: Principles of Economics, Intermediate Microeconomics, Intermediate Macroeconomics, Econometrics, Economics of Money and Finance

• **Life Course**: Social Gerontology, Social Security and Welfare for Elderly

• **Sex, Gender, and Sexuality**: Feminism and Social Work

• **Mathematics**: Calculus, Probability and Statistics, Linear Algebra

• **Quantitative Methods**: Statistics, Survival Analysis, Applied Regression Analysis, Mixed Models and Application, Biostatistics, Data Analysis and Software Application (Stata)

• **Qualitative Methods**: Qualitative Analysis Methods

• **Programming**: Python Computer Programming
	
## Teaching Assistant

• 2022 *Quantitative Reasoning*, Guanghua School of Management, PKU

• 2022 *Fundamentals of Applied Mathematics*, Workshops on Social Science Research Methods, PKU

• 2021 *Application of Multivariate Statistics*, Workshops on Social Science Research Methods, PKU

• 2021 *Content Analysis*, Workshops on Social Science Research Methods, PKU

• 2020 *Application Practice of Data Analysis*, School of Sociology and Population Studies, RUC


## Social Activities

### Social Activities

• 2022 President of academic apartment in 2022 Director of academic apartment in **Chinese LGBTQ+ community “Colors World”**. The research report I wrote as first author (Pseudonym: 胡桃/Walnut) was republished by several organizations dedicated to promoting sex and gender equality in China: [Colors World](https://colorsworld.top/articles/2022/ColorsWorld_2022-03-30%2021_%E5%8E%9F%E5%88%9B%E7%A0%94%E7%A9%B6%20_%202022%E5%B9%B4%E5%85%B3%E4%BA%8E%E8%B7%A8%E6%80%A7%E5%88%AB%E8%80%85%E7%9A%84%E7%A4%BE%E4%BC%9A%E6%80%81%E5%BA%A6%E8%B0%83%E6%9F%A5%E6%8A%A5%E5%91%8A.html), [北同文化/Beijing LGBT Center](https://mp.weixin.qq.com/s/RkhMyjMeRcHsRKX6qG_q1g), [同语/Common Language](https://mp.weixin.qq.com/s/uPPHT73HO7oNKmefTdKQoQ), [莓辣/MAYLOVE](https://mp.weixin.qq.com/s/KCdn9x4ozTZQHNzuUKt2qw)

• 2018-2019 Vice chairman of the **Student Union** of School of Sociology and Population Studies, RUC

• 2017 Editorial assistant in **Journal of Population Studies**

• 2016-2018 Joined the **Community of Think and Action dedicated in caring for workers and farmers**

### Visiting Experience

• 2018 Academic visit at *University of Toronto* as a member of the Talent Training Program of RUC.


### Volunteering

• 2018 *Volunteer* at the elephant care progam in Umphang, Thailand

• 2018 *Volunteer teaching* in Chengkou County, Chongqing, China


## Reviewer


• Reviewer: [Frontiers in public health](https://www.frontiersin.org/articles/10.3389/fpubh.2022.965017/full?&utm_source=Email_to_rerev_&utm_medium=Email&utm_content=T1_11.5e4_reviewer&utm_campaign=Email_publication&journalName=Frontiers_in_Public_Health&id=965017)

## Memberships

•  [Population Association of America](https://www.populationassociation.org/home)

•  [International Union for the Scientific Study of Population](https://www.iussp.org/)
