---
title: "Publications"
author: 
date: 
output: 
  html_document:
    toc: true
    toc_float: true
---

# Research Papers in Peer-Reviewed Publications

(*: correspondent author, +: co-first author)

### In English

• **Xiyuan Hu**, & Chao Guo\*. (2024). Temporal trends and cohort variations of gender-specific major depressive disorders incidence in China: analysis based on the age-period-cohort-interaction model. *General Psychiatry*, 37:e101479. [doi](https://gpsych.bmj.com/content/37/4/e101479).

• **Xiyuan Hu**, Dianqi Yuan, Yuyu Zeng, & Chao Guo\*. (2024). Impact of the First-Wave COVID-19 Pandemic on Medical Expenditure for Older Adults in China: Lessons from a Natural Experiment. *Journal of Aging & Social Policy*, 1-20. [doi](https://doi.org/10.1080/08959420.2024.2348967).

• **Xiyuan Hu**\*, & Heng Wang. (2024). Gender and Sexuality Disparities in Perception, Attitude and Social Intimacy Among Sinophone Youth Toward Transgender and Gender Non-Conforming Individuals: Based on an Internet Survey. *Journal of Homosexuality*, 71(14), 3254–3275. [doi](https://www.tandfonline.com/doi/full/10.1080/00918369.2023.2287031). 

• Dianqi Yuan, **Xiyuan Hu**, Yuyu Zeng, Huameng Tang, & Chao Guo\*. (2024). The early-stage impacts of shock events on adult sleep: Lessons from the COVID-19 pandemic. *Stress and Health*, e3385. [doi](https://doi.org/10.1002/smi.3385). 
	
• Chao Guo\*, Dianqi Yuan, Huameng Tang, **Xiyuan Hu**, & Yiyang Lei. (2024). Impact of a pandemic shock on unmet medical needs of middle-aged and older adults in 10 countries. *BMJ Health & Care Informatics*, 31:e100865. [doi](https://informatics.bmj.com/content/31/1/e100865). 	
	
• **Xiyuan Hu**\+, Chao Guo\+\*, Jie Liu, & Ketian Zhang. (2022). Bridging the Digital Divide: Childhood Social Relationships and Mobile Payment Use Among Chinese Middle-Aged and Older Adults. *Journal of Applied                                        Gerontology*, 41(12), 2469–2479. [doi](https://journals.sagepub.com/doi/10.1177/07334648221117771).

• Chao Guo\*, **Xiyuan Hu**, Chaofan Xu, & Xiaoying Zheng. (2022).  Association Between Olympic Games and Children’s Growth: Evidence from China. *British Journal of Sports Medicine*, 56:1110-1114. [doi](https://bjsm.bmj.com/content/56/19/1110).

• Chao Guo\*, **Xiyuan Hu**, Dianqi Yuan, Yuyu Zeng, & Peisen Yang. (2022). The Effect of COVID-19 on Public Confidence in the World Health Organization: A Natural Experiment Among 40 Countries. *Globalization and Health*, 18(1), 77. [doi](https://globalizationandhealth.biomedcentral.com/articles/10.1186/s12992-022-00872-y).

• Xinhui Zhang, **Xiyuan Hu**, Yalu Zhang, Jingjing Sun, & Gong Chen\*. (2021). Longitudinal Association Between Oral Status and Depressive Symptoms Among Chinese Older Adults - China, 2014-2018. *China CDC Weekly*, 3(40), 842-846. [doi](https://weekly.chinacdc.cn/en/article/doi/10.46234/ccdcw2021.208).


### In Chinese

• Yueping Song\*, & **Xiyuan Hu**. (2023). Nutrition Investment and Academic Performance of Rural Adolescents—Evidence from the nutrition improvement program for rural students receiving compulsory education. *Journal of Xiangtan University ( Philosophy and Social Sciences)*, 47(05), 24-31. [doi](http://www.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFD&dbname=CJFDAUTO&filename=XTDX202305004&uniplatform=OVERSEA&v=JTW6jbiO746pdFzuEUakwrapTeFjxgew5yO-SVKCOO2rOrNMY68gVkQTaE8C9nrW).

• **Xiyuan Hu**, & Chao Guo\*. (2022). The Association Between Military Experience and Health Among Older Adults Aged 60 and Above In China. *Chinese Journal of Disease Control & Prevention*, 26(1), 105. [doi](https://www.webofscience.com/wos/alldb/full-record/CSCD:7143465).

• **Xiyuan Hu**, & Chao Guo\*. (2022). The Effect of Chronic Disease, Disability, and Dementia on All-Cause Mortality Among Older Adults in China: A Population-Based Prospective Cohort Study. *Chinese Journal of Epidemiology*, 26(12), 1426-1432. [doi](https://zhjbkz.ahmu.edu.cn/cn/article/doi/10.16462/j.cnki.zhjbkz.2022.12.011). 

• **Xiyuan Hu**, Wen Cui, & Chao Guo\*. (2022). Analysis on Physical Examination Status and Its Predisposing, Enabling, Need and Healty Behavioral Influencing Factors Among Middle-aged and Older Chinese Residents. *Chinese Journal of Public Health*, 38(10), 1253-1257. [doi](https://www.zgggws.com/cn/article/doi/10.11847/zgggws1136992). 

• Long Li, Ying Tang, & **Xiyuan Hu**\*. (2022). How Living with Grandparents Affects the Health Status of Middle School Adolescents: A Multidimensional Study Based on CEPS. *Chinese Journal of Health Policy*, 15(6), 39-45. [doi](https://www.webofscience.com/wos/alldb/full-record/CSCD:7278575).

• Yueping Song\*, **Xiyuan Hu**, & Xiuchen Long. (2022). Influence of Free Nutrition Lunch Policy on Overweight of Rural Adolescents: Based on China Education Panel Survey Junior High School Cohort Data. *Chinese Journal of Epidemiology*, 43(6), 885-891. [doi](https://www.webofscience.com/wos/alldb/full-record/MEDLINE:35725346).

• Yihao, Zhao, **Xiyuan Hu**, & Chao Guo\*. (2022). Long-Term Effects of Pregnancy Exposure to Natural Disasters on Physical Health: A Review. *Chinese Journal of Public Health*, 38(08), 1082-1087. [doi](https://www.zgggws.com/cn/article/doi/10.11847/zgggws1136302).

# Book

• Chao Guo, & **Xiyuan Hu**. (2022). Econometric Method and Population Health Research. *Beijing: China Economic Publishing House*. [In Chinese]. [data & code](https://github.com/hxygoodluck/Econometric-Method-and-Population-Health-Research)

# Conference Presentations

(#: presenter)

• Mariétou Ouayogodé, & **Xiyuan Hu**\#. (Oct 2024). The Impact of Accountable Care Organization Participation on Diabetes Quality of Care and Healthcare Disparities: Insights from a Natural Experiment (2009-2018)”. *American Public Health Association Annual Meeting*, Minneapolis, Minnesota. Presented in the Poster Session.

• **Xiyuan Hu**\#, & Chao Guo. (Apr 2024). Temporal Variations and Cohort Patterns of Gender-Specific Major Depressive Disorder Incidence in China: Analysis Based on Age-Period-Cohort-Interaction Model. *Annual Meeting of the Population Association of America*, Columbus, Ohio. Presented in the Poster Session.	

• **Xiyuan Hu**, Heng Wang\#, & Chao Guo. (Apr 2023). Sex and Gender Disparities in Perception, Attitude and Social Intimacy among Sinophone Youth towards Transgender and Gender Nonconforming Individuals: Based on an Internet Survey. *Annual Meeting of the Population Association of America*, New Orleans, Louisiana. Presented in the Oral Session.

• **Xiyuan Hu**\#, & Chao Guo. (Apr 2022). Analysis on Predisposing, Enabling, Need and Health Behavioral Factors of Physical Examination among Chinese Middle Aged and Older Adults. *Annual Meeting of the Population Association of America*, Atlanta, Georgia. Presented in the Poster Session.

• **Xiyuan Hu**\#, & Chao Guo. (Dec 2021). The Journey of Awareness: The Identification Course of Chinese Male Homosexual Orientation. *International Population Conference*, Hyderabad, India. Presented in the Poster Session.

