---
title: "Self-talking"
author: 
date: 
output: 
  html_document:
    toc: true
    toc_float: true
---

## Book List

• 刘绍华 / Shaohua Liu [Taiwan]: *Passage to Manhood: Youth Migration,Heroin,and AIDS in Southwest China* 

• George Orwell [UK]: *1984*

• George Orwell [UK]: *Animal Farm*

• Claude Lévi-Strauss [France]: *Tristes Tropiques*

• Atul Gawande [US]: *Being Mortal*

• Svetlana Alexandravna Alexievich [Belarus]: *Voices From Chernobyl*

• 上野千鹤子 / Chizuko Ueno [Japan]: *Misogyny*

• Orna Donath [Israel]: *Regretting Motherhood*

• C.J. Pascoe [US]: *Dude, You’re a Fag: Masculinity and Sexuality in High School*

• Larry Nuttbrock [US]: *Transgender Sex Work and Society*

• 村上春树 / Murakami Haruki [Japan]: *Killing Commendatore*

• Gabriel García Márquez [Colombia]: *Cien años de soledad / One Hundred Years of Solitude*

• Elena Ferrante [Italy]: *L'amica geniale / My Brilliant Friend*

## Movie List

### 隐入尘烟 / Return to Dust

• 2022

• Director: 李睿珺 / Ruijun Li [China]

### L'Événement / Happening

• 2021

• Director: Audrey Diwan [France]

### Never Rerely Sometimes Always

• 2020

• Director: Eliza Hittman [US]

### 버닝 / Burning

• 2018

• Director: 이창동 / Lee Chang-dong

### The Danish Girl

• 2015

• Director: Tom Hooper [UK]

### Girl

• 2008

• Director: Lukas Dhont [Belgium]

### 4 luni, 3 săptămâni și 2 zile / 4 Months, 3 Weeks and 2 Days

• 2007

• Director: Cristian Mungiu [Rumania]

### The Wind that Shakes the Barley

• 2006

• Director: Ken Loach [UK]

• My favorite move! “It's easy to know what you are against, but quite another to know what you are for.”

### Breakfast on Pluto

• 2005

• Director: Neil Jordan [Ireland]

